### ISSUE TITLE
Trouble getting transcribe.py to work

### ISSUE THREAD

**Issue by wavymulder** [neonbjb/ocotillo#2]
Hello,

I've successfully managed to get ocotillo.py to transcribe audio via Simple CLI, but have yet to have the same success with the batch file.

Here's my traceback, I'm running it in an Anaconda env (that I named wrong :/):
```
(octotillo) C:\Users\XXXXX\ocotillo>python ocotillo\transcribe.py --path C:\Users\XXXXX\ocotillo\test --cuda=0
Traceback (most recent call last):
  File "ocotillo\transcribe.py", line 14, in <module>
    from ocotillo.dataset import AudioFolderDataset
  File "C:\Users\XXXXX\ocotillo\ocotillo\ocotillo.py", line 3, in <module>
    from ocotillo.api import Transcriber
ModuleNotFoundError: No module named 'ocotillo.api'; 'ocotillo' is not a package
```

edit: was messing around more trying to get it to work. Copied transcribe.py to the same directory as ocotillo.py, now getting a different traceback:

```
Traceback (most recent call last):
  File "transcribe.py", line 28, in <module>
    model, processor = load_model(f'cuda:{args.cuda}' if args.cuda != -1 else 'cpu', use_torchscript=True, phonetic=args.phonetic)
  File "C:\Users\XXXXX\ocotillo\ocotillo\model_loader.py", line 15, in load_model
    model = trace_torchscript_model(model_name.split('/')[-1].replace('-', '_'), 'cuda' if 'cuda' in device else 'cpu')
  File "C:\Users\XXXXX\ocotillo\ocotillo\model_loader.py", line 40, in trace_torchscript_model
    torch.jit.save(traced_model, output_trace_cache_file)
  File "C:\Users\XXXXX\anaconda3\envs\octotillo\lib\site-packages\torch\jit\_serialization.py", line 81, in save
    m.save(f, _extra_files=_extra_files)
  File "C:\Users\XXXXX\anaconda3\envs\octotillo\lib\site-packages\torch\jit\_script.py", line 693, in save
    return self._c.save(str(f), **kwargs)
RuntimeError: File torchscript/traced_wav2vec2_large_robust_ft_libritts_voxpopuli_cuda.pth cannot be opened.
```

**Comment by neonbjb** [comment]
Hey there.
This is likely because I'm frankly terrible at python packaging, I apologize for the frustrations. I think what you want to do, starting fresh, is:

```
git clone https://github.com/neonbjb/ocotillo.git
cd ocotillo
python setup.py install
```

I've fixed the second bug on the tip of main. I've also updated the readme to reflect these new instructions. Thanks for reporting this.

**Comment by wavymulder** [comment]
Thanks for getting back to me!

On running setup.py, this is what I'm getting

```
(ocotillo) C:\Users\tgdra\ocotillo>python setup.py install
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
  warnings.warn(
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-21764.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.
```

it feels like a PATH error but I'm not sure how to fix it. Have tried running Anaconda in administrator.

**Comment by neonbjb** [comment]
Hey, I've never seen something like that before. The only advice I can offer is try creating a new conda environment (it looks like you are using conda?) and re-run the commands.

**Comment by wavymulder** [comment]
I figured out the problem! I did make a new environment and forgot to reinstall Pytorch before running setup.py 

Then ran into "No audio backend is available" which I fixed by installing PySoundFile (I'm on Windows).

Now both transcribe and Ocotillo are working. Thanks again for the help.
